### PR TITLE
Fix #348

### PR DESCRIPTION
**Pull request by Larpoux**
This PR is supposed to fix @greymag PR #348.

@greymag
@bsutton 
@hyochan 

This is my first Pull Request agains the V5 😃 
Is it OK for you ?

### CODE REVIEW

**Comment by bsutton** [comment]
Can I suggest a slightly different approach.

The problem is essentially that the AAC coded was not introduced until api level 10.

If I understand correctly, selecting the DEFAULT codec results in the audio be encoded to AAC.

I'm not a big fan of the idea of a 'default' codec as its not clear what codec you will get back once recording is completed.

In the 5.0 branch I've removed any reference to a 'default' codec.

To fix this particular issue I would suggest that if the dart code passes down the AAC codec then we switch to the 'DEFAULT' codec in the java code.
We probably should put in an api version check (i.e. only do the switch if api is less than 10) just in case the meaning of 'DEFAULT' has changed over time.

This means that a user always explicitly chooses a codec, so they know what codec is being recorded, but we also support devices using < api 10.

Thoughts?

**Comment by Larpoux** [comment]
Yes, @bsutton .
Your suggestion will fix a bug when the user specify AAC, but AAC is not supported by the OS.
But I would like also that DefaultCodec will be really the OS default, and not something that we arbitrary force.

Can we do both ?

**Comment by greymag** [comment]
> The problem is essentially that the AAC coded was not introduced until api level 10.

The problem in my PR is reproduced on Android 5 (API 21).

**Comment by greymag** [comment]
About this PR.

Problem appears with default parameter `codec:  t_CODEC.CODEC_AAC`.

So, in current (v4) version it lead's to
```
codec = MediaRecorder.AudioEncoder.AAC
outputFormat = MediaRecorder.OutputFormat.AAC_ADTS
```
and this set of parameters doesn't work correctly.

If I change output to `MediaRecorder.OutputFormat.DEFAULT` - it works.

Changes in this PR probably fix problem with default `code` parameter (I can check it later on the problem device), but codec `Codec.aacADTS` still will lead to corrupted record.

**Comment by Larpoux** [comment]
Would it be OK for you to use t_CODEC.DEFAULT
and FS will use the Android default both for the Encoder and the FileFormat ?

**Comment by bsutton** [comment]
The problem with allowing a default is that there is no way to discover
what format the recording occurred in.

5.0 currently requires a codec. I would prefer to leave it that way and
find out what is actually causing this problem. That information may
indicate other changes are required.

**Comment by Larpoux** [comment]
Rejected by @bsutton .
We are now waiting for his own PR.

**Pull request closed without merging**
