### PR TITLE
Potential fix for #340

### PR DESCRIPTION
**Pull request by bsutton**
Looks like #340 is caused by a user clicking a media button before Flauto is fully initialised. 
This is likely to be prevalent on phones that map hard buttons to media events (volume/pause/resume/play).

We now discard any media button events until Flauto is fully initialised.

This pr also has fixes for the slot allocation not handling lazy initialisation in the dart code.

NOTE; this may still be an issue in the IOS code.
@Larpoux  can you take a look at the changes I've made to the slot initialisation in the SoundPlayer/SoundRecorder and TrackPlayer and replicate those changes to iOS.

Includes a number of bug fixes including for the demos.

Removed onFinished in favour of onStopped. It turns out you can't actually tell the difference as the plugin calls onFinished whether the player stops naturally or is stopped via user or api. As such the onStopped is a better verb as onFinished is mis-leading (it implies that the recording finished to completion). This will also simplify cleanup as users no longer have to hook both onStopped and onFinished.

Fixed an IllegalStateException when the player completes due to a race condition.

Upgraded to flutter 1.17 including required package changes.

### CODE REVIEW

**Comment by 3mrdev** [comment]
I am waiting to test it

**Comment by bsutton** [comment]
We are currently having conversations over how to proceed with the dev branch I've been working on.
We are have a little trouble reaching a consensus.

If you want to test it out you can do a fork/clone of my branch at bsutton/flutter_sound.
Have a look at the read.me has it has notes on migrating to the 5.0 branch (dev).

Brett

**Comment by Larpoux** [comment]
We actually have a `little` management problem.
Until this issue is fixed, I think it is not correct for you, @bsutton , to do ads for your fork in Flutter Sound project.

**Comment by bsutton** [comment]
There's fixes can probably be back ported and I've never been one to stand
in the way of a user testing code.

**Comment by Larpoux** [comment]
You told us that you consider V4 as a LTS (Long term support) version.
A crash is something completely unacceptable and we are waiting for a push into V4 from you.

Suggest to a user to use your experimental fork is irresponsible.

**Comment by bsutton** [comment]
Irresponsible?

To suggest they use it yes, to suggest they test it no.

As to a pr for the code changes I had assumed that you would do it but I
can arrange it if you want.

**Comment by Larpoux** [comment]
Yes I do want.

**Comment by bsutton** [comment]
I will try to organise it over the weekend.

**Comment by bsutton** [comment]
Superseded by #357

**Pull request closed without merging**
