### PR TITLE
Improved db calcs.

### PR DESCRIPTION
**Pull request by bsutton**
The db calcs were constantly saturating at 160db even with a low volume recording.
Also fixed some state inconsistency with method callbacks.
Improved some the exceptions been thrown.

### CODE REVIEW

**Comment by hyochan** [comment]
@bsutton Thank you for your contibution! Could you please `rebase`? There is a conflict with the `master` branch.

**Comment by bsutton** [comment]
I think this should now be correct as github is reporting that it has no conflicts.

**Comment by jam33** [comment]
What is the reasonable range for db here?  I agree that previously it was pulling 160db at very reasonable/low levels.  Now it seems the max I can register is 70db (computer speakers turned full blast right next to phone mic).  To be exact it was: 70.00061068314733.

The demo still seems to base the UI "feedback bar" (progress indicator) off of 160:
`value: 100.0 / 160.0 * (this._dbLevel ?? 1) / 100,`

So, the "green" bar never gets more than 1/2-1/3 of the way across the "red" indicator bar.

**Comment by bsutton** [comment]
80db is a reasonable range.

**Pull request merged**
