### PR TITLE
add dispose method

### PR DESCRIPTION
**Pull request by lukepighetti**
I just typed this in via GitHub editor, so it should probably be smoke tested before merging

### CODE REVIEW

**Comment by hyochan** [comment]
Hi @lukepighetti ! Nice to see you again~ :)
I'll try to go over this soon

**Comment by hyochan** [comment]
@lukepighetti Would you like to rebase your work to `master`?  Something has changed a lot by great work in #243

**Comment by lukepighetti** [comment]
@hyochan I just resolved the conflicts, does that resolve the issues?

**Comment by hyochan** [comment]
@lukepighetti Would you like to give this feature to `flutter_sound_player` and `flutter_sound_recorder`? We've migrated into files.

**Comment by Larpoux** [comment]
Hi @lukepighetti ,

1. FlutterSoundPlayer
Actually, the problem with FlutterSoundPlayer is that he function ```_removePlayerCallback()``` is not called by ```stopPlayer()``` (but it is correctly called by ```audioPlayerFinished()```  )
I am adding this call in ```stopPlayer()```
Then, the function ```_removePlayerCallback()``` closes correctly the ```playerController```
I add also the call to ```_removePlayerCallback()``` by ```release()```.

2. FlutterSoundRecorder
Actually, the functions ```_removeRecorderCallback()``` and ```_removeDbPeakCallback()``` are correctly called by ```_stopRecorder()```
I am adding those two calls inside ```release()```
 
Does this seem correct for you ?

**Comment by Larpoux** [comment]
_removeRecorderCallback(),  _removeDbPeakCallback and _removePlayerCallback()  are now called during the function ```release()```. (V3.1.6)

**Pull request closed without merging**
