### PR TITLE
WIP: Allow change of ALL settings in Example App

### PR DESCRIPTION
**Pull request by ened**
This is still in WIP and did uncover quite a few bugs with the implementation for me.

For example, setting invalid Audio recording encodings will break the plugin (and any future use) + it did not return a descriptive error code back to the example (or the example did not show it).

Implementation bug fixes will be provided in separate PRs as I discover them.

Also need to decide
- if we want to filter iOS/Android settings on the appropriate platforms (I guess it's fine to show all).
- if bitrate/number of channels/sample rate settings should be dropdowns instead

@hyochan WDYT

### CODE REVIEW

**Comment by hyochan** [comment]
@ened Thanks for continuous support for your `PR`. 
1. if we want to filter iOS/Android settings on the appropriate platforms (I guess it's fine to show all).
   - Agree with showing all.
2. if bitrate/number of channels/sample rate settings should be dropdowns instead
   - The dropdown shouldn't matter since this is just an example project. Do this as much as your favor. Thanks for your additional concern in `example` too.

**Comment by hyochan** [comment]
@ened Is this ready to be merged?

**Comment by ened** [comment]
Still WIP as I’d like to add proper error reporting (and handling in example) as well. Like said in the initial comment, setting invalid config will kill the plugin permanently currently.

**Comment by hyochan** [comment]
Since this `PR` haven't been updated for a while, I'll close it!

**Pull request closed without merging**
