### PR TITLE
Revert "Android command queue for recording related tasks"

### PR DESCRIPTION
**Pull request by hyochan**
Reverts dooboolab/flutter_sound#63

This `PR` doesn't seem to work as expected.
y3qKXMrDmk

### CODE REVIEW

**Comment by ened** [comment]
@hyochan what are we looking at? Your screen recording suggestions the recorded audio file should be played back after recording stopped?
Did you collect any logs?

**Comment by hyochan** [comment]
@ened Sorry. I've just quickly merged and tested this in `example` project and it didn't record and played well. Even when I stopped recording by pressing the stop button, I couldn't re-record again.

**Comment by ened** [comment]
@hyochan Understood. Will double check and submit a new PR.

**Comment by hyochan** [comment]
Thanks. Next time I will test before a merge. Sorry that I was running out of time.

**Pull request merged**
