### PR TITLE
setAudioMeterToAmbient

### PR DESCRIPTION
**Pull request by lukepighetti**
This allows the package consumer to immediately set the audio meter to ambient, iOS only implementation so far.

Addresses https://github.com/dooboolab/flutter_sound/issues/251

Apologies for the large diff, I didn't know this package wasn't using `dartfmt`

### CODE REVIEW

**Comment by Larpoux** [comment]
This pull request seems interesting.
But I wonder what to do for Android ?

**Comment by hyochan** [comment]
@lukepighetti Same question as @Larpoux

**Comment by lukepighetti** [comment]
If I'm being honest I have no idea what to do on android or if it's even necessary. I know that's not helpful but that's what I've got at this moment.

**Comment by lukepighetti** [comment]
Looks like I won't be getting around to nailing this down on Android. I won't be upset if you close this out. Thank you for your time.

**Comment by Larpoux** [comment]
No, do not close this issue until we look to that seriously.
But time is really a problem. I have too many things in the pipeline...

**Comment by Larpoux** [comment]
Hi @lukepighetti ,

I am looking to your Pull Request. 
I am wondering if instead for adding a new API verb, it would be good to always do a ```isMeteringEnabled: true``` when the App call the API verb ```setDbLevelEnabled(true)```

I guess that if the App wants to control the amplitude meter, this one must be accurate, even if it means some CPU eating.

**Comment by Larpoux** [comment]
We added the iOS call to ```setMeteringEnabled:YES``` in ```setDbLevelEnabled(true)```.

**Pull request closed without merging**
