### PR TITLE
[FLAUTO]

### PR DESCRIPTION
**Pull request by Larpoux**
OK, guys and girls.
I think I am ready for an integration inside the master branch.
The only, **BIG** issue not fixed is #234 . This issue is very, very serious. I had to disable the `Resume` feature on `Diglot Korean` (my own App). This is really very bad 😞 .
But I think this bug is not related to Flauto, and is already present in the actual Master branch.

@salvatore373 : Can you look to this Pull Request and tell us if you have remarks ?
@hyochan : I hope that you will like this PR and integrate it soon in the Master Branch.

### CODE REVIEW

**Comment by Larpoux** [comment]
@hyochan : 
Now, flutter_sound has two different modules:
- The legacy `flutter_sound` with some improvments like some tools to control the Audio-focus 
- `Flauto`, wich adds @salvatore373 improvements .

Those two modules are completely separated. This has two benefits:
- Separated functionalities means easier maintenance
- The legacy `flutter_sound` module is totally backward compatible

My project would be to split again the legacy `flutter_sound` module into two different modules : 
- FlutterSoundRecorder
- FlutterSoundPlayer
Those two functionalities are not related together, and there is no reason to have just one module.
Having two smaller modules will let the maintenance easier.

For having backward compatibility, the `FlutterSoundPlayer` module will be called simply `FlutterSound` and will inherit from `flutterSoundRecorder`.
But new developer will be encouraged to use the `FlutterSoundRecorder` module for recording.

We will have three modules : 
- `Flauto` (which inherit from `FlutterSoundPlayer)
- `FlutterSoundPlayer` (which inherit from `FlutterSoundRecorder` for backward compatibility)
- `FlutterSoundRecorder`

Then, I think it will be easier to address #232 (which has been closed by its creator, but for me this issue is still valid and interesting).

**Comment by hyochan** [comment]
@Larpoux @salvatore373 Thanks for your time for bringing up fabulous features. I really appreciate all your work given to `flutter_sound` for a long time and I'll do my best to check this `PR` so that your times are not wasted. I will try to finish this review in March!

Thanks again to all you wonderful people 🥇

**Comment by Larpoux** [comment]
Hyo, I suggest to maintain two branches : 
- `Stable` (the actual Master branch)
- `Master` (the Flauto branch)

and merge the master branch to the stable branch if/when the master branch is accepted by the community as stable.

**Comment by bsutton** [comment]
Can I suggest you consider renaming the Flauto module to something like FlutterSoundPlayerV2.

The name flauto doesn't convey any useful information. 

If we use my suggested naming convention then we end up with
FlutterSoundPlayer
FlutterSoundPlayerV2
FlutterSoundRecorder

Selecting the appropriate module is now easy.

**Comment by Larpoux** [comment]
> Hyo, I suggest to maintain two branches :
> 
> * `Stable` (the actual Master branch)
> * `Master` (the Flauto branch)
> 

@hyochan : what do you think of this ? I think it will not give us much more maintenance work.
And it will be easier for us to split the Problem Reports between 'bug in Master Branch' and 'bug in stable branch'.

I am ready to do some maintenance and development on the `Master Branch`.
It will be more comfortable, for me to know that I will no break the `Stable Branch`.
If we do that, maybe good if I accept your invitation to be a flutter_sound maintainer. 😸

**Comment by Larpoux** [comment]
@hyochan is actually very, very busy for flutter_sound maintenance.
In the interim I suggest that we use the `flauto` fork.

The sources [are here](https://github.com/Canardoux/flauto).
- branch `stable` is the actual flutter_sound (V 2.1.1). This is the **gamma** branch.
- branch `beta` is the new plugin with advance features (V 3.0.1). This is the **beta** branch.
- branch `master` is just for the project development and not to be used. This is the **alpha** branch.

The flauto plugin is published. In your pub spec.yaml : 
```
dependencies:
  flutter:
    sdk: flutter
  flauto: ^3.0.1+1
```

**Comment by hyochan** [comment]
@Larpoux Sounds nice that some of them can try newer version beforehand. I like the idea of separating the branches too. Shall we test the `beta` release for this plugin and further review this ongoing?
If you separate the `pub` plugin to `flauto`, users may get confused about what plugins to use since they are not always focusing on our work. What about just releasing this to the `beta`? How do you think?

**Comment by hyochan** [comment]
Merged 🎉

**Comment by hyochan** [comment]
Released 3.0.0 🎉

**Pull request merged**
