### PR TITLE
Fix issue #254

### LINKED ISSUE #254: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object
### Version of flutter_sound
3.0.0

## flutter doctor
 isAudioOn: The number of audio connected devices 0
03-26 16:08:17.714  2200  3152 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
03-26 16:08:17.714  2200  3152 D HeadsetService:  isAudioOn: The number of audio connected devices 0
03-26 16:08:17.717 21074 21074 D AndroidRuntime: Shutting down VM
03-26 16:08:17.717 21074 21074 E AndroidRuntime: FATAL EXCEPTION: main
03-26 16:08:17.717 21074 21074 E AndroidRuntime: Process: re.distantfutu.journal, PID: 21074
03-26 16:08:17.717 21074 21074 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:483)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:402)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4070)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	... 8 more

### PR DESCRIPTION
**Pull request by Larpoux**
This will probably fix #254

### CODE REVIEW

**Comment by hyochan** [comment]
@Larpoux Would you like to change the license?

**Comment by Larpoux** [comment]
Oh, yesssssss! Pleeeeease. If you do not mind, of course.

**Comment by hyochan** [comment]
I dont mind with your opinion since u r the core contributor~ You can chanfe the license in this PR with the readme!

**Comment by Larpoux** [comment]
I am currently finishing #232 and #250. I hope it will be finished in a few hours.
But probably you will be in bed at this timer 👀

**Comment by hyochan** [comment]
@Larpoux  So how is this now?

**Comment by Larpoux** [comment]
I sent a new PR #257 .
This is a major re-design of the architecture. Backward compatibility is respected.

I am currently working on Pause/Resume during recording.
I think I will finish this evening, or tomorrow.
This feature is really wanted by many developers.

**Comment by hyochan** [comment]
Thanks again for your concern 👍  So may I merge this without and changes in the license?

**Comment by Larpoux** [comment]
Yes, I changed the license, because you told me that I may do it.

**Comment by hyochan** [comment]
Well but I can't see any changes in license in this PR.

**Comment by Larpoux** [comment]
I changed the LICENSE file, and all the headers in the sources files.
(I hope ;-) )

**Comment by hyochan** [comment]
image

Above is only file changes I can see in this `PR`. Am I seeing something different?

**Comment by Larpoux** [comment]
I was talking about #257. Which is a really great change.
#256 is just a very little patch to fix #254 .  
You can apply #256 without any doubt.
#257 is more serious job.

**Pull request merged**
