### PR TITLE
Release/3.1.0

### PR DESCRIPTION
**Pull request by hyochan**
Bringing new `PR` from #257 since I don't have permission to @Larpoux repo.

### CODE REVIEW

**Comment by hyochan** [comment]
@Larpoux Could you push new commits to this branch? Since I don't have permission to #257

**Comment by hyochan** [comment]
Also, I've fixed `seek` feature in `TrackPlayer`.

**Comment by hyochan** [comment]
@Larpoux `3.1.0` is released 🎉

**Comment by Larpoux** [comment]
YEAH!!!!!

**Pull request closed without merging**
